export const LOGIN_TEXT_CHANGED = 'LOGIN_TEXT_CHANGED';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CHANGE_TAB_NAV = 'CHANGE_TAB_NAV';
export const ADD_DATA_FOR_SAVING = 'ADD_DATA_FOR_SAVING';
export const SET_ACTIVE_SURVEY = 'SET_ACTIVE_SURVEY';
export const SET_LOCAL_SURVEYS = 'SET_LOCAL_SURVEYS';
export const RESET_SURVEY_REDUCER = 'RESET_SURVEY_REDUCER';